apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinterface
  namespace: vpnbook
  labels:
    app: myinterface
spec:
  replicas: 3
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: myinterface
  template:
    metadata:
      labels:
        app: myinterface
    spec:
      volumes:
        - emptyDir: { }
          name: log
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      imagePullSecrets:
        - name: codeup-registry
      containers:
        - image: registry.cn-beijing.aliyuncs.com/biyao/spider:myinterface-v1
          imagePullPolicy: IfNotPresent
          name: myinterface
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          args:
            - uvicorn
            - main:app
            - --host
            - 0.0.0.0
            - --port
            - "8000"
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            - mountPath: /usr/local/crawler/logs
              name: log
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: myinterface
  namespace: vpnbook
  labels:
    app: myinterface
spec:
  type: NodePort
  selector:
    app: myinterface
  ports:
    - name: http
      port: 8000
      nodePort: 30896
      protocol: TCP
      targetPort: http
